name = "BlanketCon '25"
author = "ModFest"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdf6d2536892500befbae2f007fa7779182098aa5b8366ea053d52faf7b86042"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
unsup = "1.0-rc2"
